### ISSUE TITLE
DeezerOptions must not be empty.

### ISSUE THREAD

**Issue by NedcloarBR** [WearifulCupid0/erela.js-deezer#1]
(node:14200) UnhandledPromiseRejectionWarning: TypeError: DeezerOptions must not be empty.
    at check (E:\Projetos\Discord Bots\N-D-B Definitive Edition\Bot\node_modules\erela.js-deezer\dist\plugin.js:35:15)
    at new Deezer (E:\Projetos\Discord Bots\N-D-B Definitive Edition\Bot\node_modules\erela.js-deezer\dist\plugin.js:49:9)     
    at ReadyEvent.run (E:\Projetos\Discord Bots\N-D-B Definitive Edition\Bot\Src\Events\Ready\Erela.js:33:9)
    at Client.emit (events.js:327:22)
    at WebSocketManager.triggerClientReady (E:\Projetos\Discord Bots\N-D-B Definitive Edition\Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (E:\Projetos\Discord Bots\N-D-B Definitive Edition\Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (E:\Projetos\Discord Bots\N-D-B Definitive Edition\Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:197:14)
    at WebSocketShard.emit (events.js:315:20)
    at WebSocketShard.checkReady (E:\Projetos\Discord Bots\N-D-B Definitive Edition\Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (E:\Projetos\Discord Bots\N-D-B Definitive Edition\Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:447:16)
    at WebSocketShard.onMessage (E:\Projetos\Discord Bots\N-D-B Definitive Edition\Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (E:\Projetos\Discord Bots\N-D-B Definitive Edition\Bot\node_modules\ws\lib\event-target.js:132:16)  
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (E:\Projetos\Discord Bots\N-D-B Definitive Edition\Bot\node_modules\ws\lib\websocket.js:825:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (E:\Projetos\Discord Bots\N-D-B Definitive Edition\Bot\node_modules\ws\lib\receiver.js:437:14)     
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of 
an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14200) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that 
are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by WearifulCupid0** [comment]
Thanks for your Issue, I'm going to fix this.
